OPENROUTER_API_KEY = "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"
GITHUB_TOKEN = "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"
GITHUB_REPO  = "mayukhkondepudi-a11y/Lifestyle-Fund-POC"
GMAIL_SENDER = "mayukhkondepudi@gmail.com"
GMAIL_APP_PASS = "nkvxcubdjtctqeud"
STREAMLIT_APP_URL = "https://pickr-trackr.streamlit.app"