OPENROUTER_API_KEY = "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"
GITHUB_TOKEN = "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"
GITHUB_REPO  = "mayukhkondepudi-a11y/Lifestyle-Fund-POC"
GMAIL_SENDER = "mayukhkondepudi@gmail.com"
GMAIL_APP_PASS = "nkvxcubdjtctqeud"
STREAMLIT_APP_URL = "https://lifestyle-fund-poc-sqirxewsib7u2fmfqimphm.streamlit.app"